import { useEffect, useRef, useState } from 'react';
import { Info, Download } from 'lucide-react';
import exifr from 'exifr';
import { DocumentToolLayout } from '@/components/DocumentToolLayout';
import { Card, SoftCard } from '@/components/ui/Card';
import { FileDropzone } from '@/components/document/FileDropzone';
import { ProcessingIndicator } from '@/components/document/ProcessingIndicator';
import { Button } from '@/components/ui/Button';
import { getDocumentToolBySlug } from '@/data/documentToolsRegistry';
import { useToolHistory, formatBytes } from '@/hooks/useToolHistory';
import { downloadBlob, loadImage, stripExtension } from '../logic/fileUtils';

const tool = getDocumentToolBySlug('image-metadata-viewer')!;

const article = {
  intro: 'Image Metadata Viewer reads the EXIF metadata embedded in an image file \u2014 camera settings, dimensions, capture details, and more \u2014 and displays it right in your browser, with an option to export everything as a JSON file. The image itself is never uploaded anywhere.',
  whyItMatters: 'Photos can carry more information than what\u2019s visible on screen, including camera model, exposure settings, timestamps, and sometimes GPS location. Viewing that metadata helps you understand exactly what a photo contains \u2014 useful before sharing a photo publicly, or when you need to confirm technical details like resolution or capture date for an assignment.',
  howItWorks: [
    'Select an image \u2014 JPEG and other formats that support EXIF data work best; many PNGs and most screenshots carry little or no EXIF metadata by design.',
    'The tool reads embedded EXIF metadata directly in your browser using a local parsing library; nothing is sent to a server.',
    'Every readable metadata field \u2014 dimensions, camera model, exposure settings, timestamps, and more, if present \u2014 is listed alongside the file name, size, and pixel dimensions.',
    'Use "Export JSON" to download the full metadata result (including file info and all parsed EXIF fields) as a `.json` file for reference or record-keeping.',
  ],
  examples: [
    { title: 'Checking before sharing a photo', body: 'View a photo\u2019s metadata to see whether it contains location or device details before posting it publicly.' },
    { title: 'Confirming technical details for a report', body: 'Check a photo\u2019s capture date, resolution, and camera settings when you need to reference them accurately for a lab report or portfolio submission.' },
  ],
  mistakes: [
    'Assuming every image has metadata \u2014 screenshots, many web-downloaded images, and some PNGs carry little to no EXIF data, which is expected behavior, not a tool error.',
    'Expecting this tool to remove metadata \u2014 it only reads and displays what\u2019s already embedded; it does not edit or strip anything from the original file.',
  ],
  tips: [
    'If a photo shows location metadata you don\u2019t want to share, use an image editor (or re-save/re-export the photo through most photo apps) to strip metadata before posting it, since this tool is view-only.',
    'Use "Export JSON" if you need to keep a record of a photo\u2019s metadata separately from the image file itself.',
  ],
  faqs: [
    { question: 'Can this tool remove metadata?', answer: 'No \u2014 it only displays existing metadata; it does not edit or strip it from the file. If you need to remove metadata before sharing a photo, use a dedicated photo editor or your device\u2019s share/export options that offer a "remove location/metadata" toggle.' },
    { question: 'Is the image uploaded to view its metadata?', answer: 'No \u2014 metadata is read locally in your browser using a client-side parsing library, and the file never leaves your device.' },
    { question: 'Can I save the metadata results?', answer: 'Yes \u2014 use the "Export JSON" button to download all of the parsed metadata (file info plus every EXIF field found) as a `.json` file.' },
    { question: 'Why does my screenshot show no metadata?', answer: 'That\u2019s expected \u2014 screenshots are generated by the operating system rather than a camera, so they typically don\u2019t carry EXIF fields like camera model or exposure settings.' },
  ],
  related: [
    { label: 'Image Compressor', href: '/document-tools/image-compressor' },
    { label: 'Image Format Converter', href: '/document-tools/image-format-converter' },
  ],
};

interface MetadataResult {
  fileName: string;
  fileSize: number;
  width: number;
  height: number;
  type: string;
  exif: Record<string, unknown> | null;
}

export default function ImageMetadataViewerPage() {
  const [meta, setMeta] = useState<MetadataResult | null>(null);
  const [previewUrl, setPreviewUrl] = useState('');
  const [status, setStatus] = useState<'idle' | 'processing' | 'success' | 'error'>('idle');
  const [errorMsg, setErrorMsg] = useState('');
  const { addEntry } = useToolHistory();
  const previewUrlRef = useRef('');

  useEffect(() => () => {
    if (previewUrlRef.current) URL.revokeObjectURL(previewUrlRef.current);
  }, []);

  async function handleFile(files: File[]) {
    const file = files[0];
    if (!file) return;
    if (!file.type.startsWith('image/')) {
      setErrorMsg('Please choose an image file.');
      setStatus('error');
      return;
    }
    setStatus('processing');
    try {
      const url = URL.createObjectURL(file);
      const img = await loadImage(url);
      let exif: Record<string, unknown> | null = null;
      try {
        exif = await exifr.parse(file);
      } catch {
        exif = null;
      }
      if (previewUrlRef.current) URL.revokeObjectURL(previewUrlRef.current);
      previewUrlRef.current = url;
      setPreviewUrl(url);
      setMeta({ fileName: file.name, fileSize: file.size, width: img.width, height: img.height, type: file.type, exif });
      addEntry({ tool: tool.name, toolSlug: tool.slug, fileName: file.name, sizeLabel: formatBytes(file.size) });
      setStatus('success');
    } catch {
      setErrorMsg('Could not read this image file.');
      setStatus('error');
    }
  }

  function downloadJson() {
    if (!meta) return;
    const json = JSON.stringify({ ...meta, exif: meta.exif ?? {} }, null, 2);
    downloadBlob(new Blob([json], { type: 'application/json' }), `${stripExtension(meta.fileName)}-metadata.json`);
  }

  function reset() {
    setMeta(null);
    setPreviewUrl('');
    setStatus('idle');
  }

  const exifEntries = meta?.exif ? Object.entries(meta.exif).filter(([, v]) => v !== undefined && v !== null && typeof v !== 'object') : [];

  return (
    <DocumentToolLayout
      toolName={tool.name} tagline={tool.tagline} description={tool.description}
      path="/document-tools/image-metadata-viewer" icon={Info} breadcrumb={{ label: 'Image Metadata Viewer' }} toolSlug={tool.slug} article={article}
    >
      <Card>
        {meta ? (
          <div className="grid sm:grid-cols-[200px_1fr] gap-6">
            <img src={previewUrl} alt={meta.fileName} className="w-full rounded-xl border border-navy-100 dark:border-white/10 object-cover aspect-square" />
            <div>
              <div className="flex flex-wrap items-start justify-between gap-3 mb-4">
                <div className="min-w-0">
                  <p className="font-semibold break-words">{meta.fileName}</p>
                  <p className="text-sm text-navy-500 dark:text-ink-500">{formatBytes(meta.fileSize)} · {meta.width}×{meta.height}px · {meta.type}</p>
                </div>
                <div className="flex flex-wrap gap-2">
                  <Button size="sm" variant="outline" icon={<Download size={14} />} onClick={downloadJson}>Export JSON</Button>
                  <Button size="sm" variant="ghost" onClick={reset}>Reset</Button>
                </div>
              </div>

              {exifEntries.length === 0 ? (
                <SoftCard>
                  <p className="text-sm text-navy-500 dark:text-ink-500">No EXIF metadata found — this image may have been stripped of metadata, or the format doesn't support it (common for screenshots and web-optimized images).</p>
                </SoftCard>
              ) : (
                <div className="grid sm:grid-cols-2 gap-2 max-h-80 overflow-y-auto pr-1">
                  {exifEntries.map(([key, value]) => (
                    <div key={key} className="rounded-lg border border-navy-100 dark:border-white/10 px-3 py-2">
                      <p className="text-[11px] uppercase tracking-wide text-navy-400 dark:text-ink-500">{key}</p>
                      <p className="text-sm font-medium truncate">{String(value)}</p>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        ) : (
          <>
            <FileDropzone accept="image/*" label="Drop an image here" hint="Reads EXIF metadata if present" onFiles={handleFile} />
            <div className="mt-4">
              <ProcessingIndicator status={status} message={status === 'error' ? errorMsg : 'Reading metadata...'} />
            </div>
          </>
        )}
      </Card>
    </DocumentToolLayout>
  );
}
