export function usePrint() {
  function printResult(toolName: string, summary: string) {
    const win = window.open('', '_blank', 'width=480,height=640');
    if (!win) return;
    win.document.write(`
      <!doctype html>
      <html>
        <head>
          <title>${toolName} — ALLROUNDER HELPER</title>
          <style>
            body { font-family: -apple-system, Inter, sans-serif; padding: 40px; color: #0a0e1a; }
            h1 { font-size: 20px; margin-bottom: 4px; }
            p.tag { color: #7d84ac; margin-top: 0; margin-bottom: 24px; font-size: 13px; }
            pre { white-space: pre-wrap; font-family: inherit; font-size: 15px; line-height: 1.7; border-top: 1px solid #eceefa; padding-top: 16px; }
            footer { margin-top: 40px; font-size: 11px; color: #b7bcda; }
          </style>
        </head>
        <body>
          <h1>${toolName}</h1>
          <p class="tag">Generated by ALLROUNDER HELPER</p>
          <pre>${summary.replace(/</g, '&lt;')}</pre>
          <footer>allrounderhelper.vercel.app</footer>
        </body>
      </html>
    `);
    win.document.close();
    win.focus();
    win.print();
  }

  return { printResult };
}
