import { buildPdfTextDocument } from '@/lib/pdfTextDocument';
import { useToast } from '@/components/ToastProvider';
import { downloadBlob } from '@/features/document/logic/fileUtils';

export function useResultPdfExport() {
  const { showToast } = useToast();

  async function exportPdf(toolName: string, summary: string) {
    try {
      const bytes = await buildPdfTextDocument({
        title: toolName,
        subtitle: 'Generated by ALLROUNDER HELPER',
        sections: [{ body: summary }],
      });
      const blob = new Blob([bytes as BlobPart], { type: 'application/pdf' });
      downloadBlob(blob, `${toolName.toLowerCase().replace(/\s+/g, '-')}-result.pdf`);
      showToast('PDF downloaded');
    } catch {
      showToast('Could not generate the PDF', 'error');
    }
  }

  return { exportPdf };
}
