/**
 * Suggested follow-up quick-replies shown as chips under the latest assistant message.
 *
 * Deliberately NOT generated by an extra AI call — that would silently burn one more
 * message against the user's daily limit for every response, which is the kind of
 * dishonest-by-implication pattern this app avoids (see PROJECT_BACKLOG notes on
 * "stay grounded in real local data"). Instead this is a small deterministic heuristic:
 * a handful of chat-mode-aware defaults, plus one contextual suggestion when the
 * assistant's own reply signals a natural next step (offered a list/steps, code, or a
 * question of its own). Cheap, instant, no network round-trip, never wrong about cost.
 */

const DEFAULT_SUGGESTIONS = ['Explain that more simply', 'Give me an example', 'Summarize the key points'];

const MODE_SUGGESTIONS: Record<string, string[]> = {
  study: ['Quiz me on this', 'Explain it like I\u2019m new to the topic', 'Break this into study steps', 'Compare this with a related concept'],
  coding: ['Show a working example', 'What are the edge cases?', 'How would I test this?'],
  social: ['Give me 3 more hook variations', 'Turn this into a caption', 'Suggest relevant hashtags'],
  content: ['Give me 3 title options', 'Turn this into a script outline', 'Suggest a thumbnail idea'],
  resume: ['Tighten this into one bullet point', 'Make it more quantified', 'Rewrite for a different role'],
  career: ['What should I do next?', 'Turn this into an action plan', 'What questions should I ask?'],
};

/**
 * Returns up to 3 short quick-reply prompts for the composer, based on the active chat
 * mode and (lightly) the assistant's last reply. `replyContent` is optional — omit it to
 * get pure mode defaults.
 */
export function getFollowUpSuggestions(chatModeId: string, replyContent?: string): string[] {
  const base = MODE_SUGGESTIONS[chatModeId] ?? DEFAULT_SUGGESTIONS;
  if (!replyContent) return base.slice(0, 3);

  const contextual: string[] = [];
  const hasCode = /```/.test(replyContent);
  const hasList = /(^|\n)\s*[-*\d]/.test(replyContent);

  if (hasCode && !contextual.includes('Explain how this code works')) contextual.push('Explain how this code works');
  if (hasList && chatModeId !== 'study') contextual.push('Turn this into a checklist');

  // Contextual suggestions take priority (they're specific to what just happened),
  // then fill remaining slots from the mode defaults, deduped, capped at 3.
  const merged = [...contextual, ...base].filter((s, i, arr) => arr.indexOf(s) === i);
  return merged.slice(0, 3);
}
